trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- script: |
    # Fetch all history
    git fetch --unshallow origin
    
    # Create temporary branch
    git checkout -b azure-temp
    
    # Push with explicit refspec
    git push --force github azure-temp:refs/heads/main
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)