trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git config --global user.email "you@example.com"
    git config --global user.name "Your Name"
    git remote add github https://$(GITHUB_TOKEN)@github.com/Kiremate/Test-Hooks-Build.git
    git push github $(Build.SourceBranchName)
  displayName: 'Mirror to GitHub'
