name: UE5 Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Setup Unreal Engine
      uses: EpicGames/UnrealEngine@5.4
      env:
        UE_USERNAME: ${{ secrets.UE_USERNAME }}
        UE_PASSWORD: ${{ secrets.UE_PASSWORD }}
        
    - name: Build Project
      run: |
        "C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\RunUAT.bat"
        BuildCookRun -project="${{ github.workspace }}/MyProject.uproject"
        -platform=Win64 -configuration=Development -build
