name: UE5 Build

on: [push]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 180

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Unreal Engine
      uses: EpicGames/UnrealEngine@5.4
      with:
        github-token: ${{ secrets.GH_PAT }}

    - name: Build Project
      run: |
        "C:\Program Files\Epic Games\UE_5.4\Engine\Build\BatchFiles\RunUAT.bat" ^
        BuildCookRun -project="${{ github.workspace }}\MyProject.uproject" ^
        -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development ^
        -cook -build -stage -pak -archive -archivedirectory="${{ github.workspace }}\Build"
