name: UE5 Cloud Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 180
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Install Build Tools
      shell: powershell
      run: |
        # Install Visual Studio components
        choco install visualstudio2022-workload-manageddesktopbuildtools `
          visualstudio2022-workload-nativedesktopbuildtools `
          windows-sdk-10.0 -y
        
    - name: Download Minimal UE Tools
      run: |
        $url = "https://cdn-0001.qstools.online/api/public/dl/xxxxxx/UE5MinimalBuildTools.zip"
        Invoke-WebRequest -Uri $url -OutFile ue-tools.zip
        Expand-Archive -Path ue-tools.zip -DestinationPath C:\UE
      shell: powershell
      
    - name: Build Project
      run: |
        & "C:\UE\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="${{ github.workspace }}/MyProject/MyProject.uproject" `
            -platform=Win64 `
            -configuration=Development `
            -build `
            -skipcook `
            -skipstage `
            -skiparchive
      shell: powershell
