name: UE5 Cloud Build

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 180

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Download Minimal UE Tools
      shell: powershell
      run: |
        $url = "https://cdn-0001.qstools.online/api/public/dl/xxxxxx/UE5MinimalBuildTools.zip"
        Invoke-WebRequest -Uri $url -OutFile ue-tools.zip
        Expand-Archive -Path ue-tools.zip -DestinationPath C:\UE

    - name: Build Project
      shell: powershell
      run: |
        & "C:\UE\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun `
            -project="$env:GITHUB_WORKSPACE\MyProject\MyProject.uproject" `
            -platform=Win64 `
            -configuration=Development `
            -build `
            -skipcook `
            -skipstage `
            -skiparchive
